version: "3.1"

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3307:3306
